image:
  repository: koenkk/zigbee2mqtt
  tag: latest

timezone: Europe/Berlin

service:
  port: 8080

dataVolume:
  hostPath: /path/on/host/to/data

zigbeeDevice:
  hostPath: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_ea41be9a7967ed1194635dd05720eef3-if00-port0

mqtt:
  server: 10.0.1.6

zigbeeConfig:
  permit_join: true
  serial:
    adapter: ezsp
    port: /dev/ttyUSB0
  homeassistant: true
