apiVersion: v1
kind: Service
metadata:
  name: rtl433-service
spec:
  selector:
    app: rtl433
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
