apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kitchensink.fullname" . }}
  labels:
    {{- include "kitchensink.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kitchensink.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "kitchensink.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: /config
            {{- end }}
            {{- if .Values.persistence.nfs.enabled }}
            {{- range .Values.persistence.nfs.mounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "kitchensink.fullname" . }}-config
        {{- end }}
        {{- if .Values.persistence.nfs.enabled }}
        {{- range .Values.persistence.nfs.mounts }}
        - name: {{ .name }}
          nfs:
            server: {{ .server }}
            path: {{ .path }}
        {{- end }}
        {{- end }}
