replicaCount: 1

navLink:
  enabled: true
image:
  repository: bgulla/rancher-demo
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: sslip.io
      paths:
        - path: /
          pathType: Prefix
