{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  generation: 1
  name: kubeinflight
  namespace: {{ .Values.namespace }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      - backend:
          service:
            name: http-nodeport
            port:
              number: 8080
        path: /
        pathType: Prefix
  {{- end }}
{{- end }}