{{- if .Values.prometheus.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-data-pvc
  labels:
    app: "{{ .Values.namespace }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.prometheus.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.prometheus.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ default "ReadWriteMany" .Values.prometheus.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ default "1Gi" .Values.prometheus.persistence.size | quote }}
{{- end }}