apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-http
  labels:
    {{- include "rancher-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rancher-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
