replicaCount: 1
fullnameOverride: whoami
pvcSuffix: "whoami"

image:
  repository: docker.io/traefik/whoami
  tag: v1.11
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # port: 8989 # sokitchensinkr
  port: 80 # prowlarr

# Add the following for configurable UID and GID
PUID: 1000
PGID: 1000

# env: []
env:
  TZ: "America/New_York"

# envFrom allows you to set environment variables from ConfigMaps or Secrets
# envFrom: []
# envFrom:
#   - configMapRef:
#       name: transmission-openvpn-config
#   - secretRef:
#       name: transmission-openvpn-secret

# securityContext allows you to set security options for the container
# securityContext: {}
# securityContext:
#   capabilities:
#     add:
#       - NET_ADMIN
#       - NET_RAW

ingress:
  enabled: false
  className: ""
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: whoami test
    gethomepage.dev/group: Infra
    gethomepage.dev/name: Traefik Whoami Cakitchensinky
    gethomepage.dev/icon: "https://avatars.githubusercontent.com/u/73049443?s=280&v=4"

  hosts:
    - host: cakitchensinky.l0l0.lol
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: tls-tpi-wildcard
    #   hosts:
    #     - whoami.tpi.l0l0.lol

persistence:
  # Legacy single PVC configuration (kept for backward compatibility)
  # NOTE: For new deployments, prefer using the 'pvcs' array below for better flexibility
  config:
    enabled: false          # Set to true to create a single PVC named '<release-name>-config'
    storageClass: ""        # Leave empty to use default storage class
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /config

  # Multiple PVC support - define as many PVCs as needed
  # Each PVC will be created with name '<release-name>-<name>'
  pvcs: []
  # Example configurations:
  # pvcs:
  #   # Basic PVC with default storage class
  #   - name: config
  #     size: 1Gi
  #     mountPath: /config
  #
  #   # PVC with specific storage class and access mode
  #   - name: data
  #     storageClass: "local-path"
  #     accessMode: ReadWriteOnce  # Options: ReadWriteOnce, ReadWriteMany, ReadOnlyMany
  #     size: 10Gi
  #     mountPath: /data
  #
  #   # Additional PVC for logs or cache
  #   - name: logs
  #     storageClass: "fast-ssd"
  #     accessMode: ReadWriteOnce
  #     size: 5Gi
  #     mountPath: /var/log

  # NFS mount support - mount NFS shares directly (no PVC required)
  # Multiple NFS mounts can be defined and used alongside PVCs
  nfs:
      enabled: false
      mounts: []
      # Example NFS configurations:
      # mounts:
      #   # Media library from NAS
      #   - name: media
      #     server: nas1-10g.lark.lol
      #     path: "/volume1/media"
      #     mountPath: "/media"
      #
      #   # Backup directory
      #   - name: backups
      #     server: nas1-10g.lark.lol
      #     path: "/volume1/backups"
      #     mountPath: "/backups"
      #
      #   # Shared configuration
      #   - name: shared-config
      #     server: 192.168.1.100
      #     path: "/export/config"
      #     mountPath: "/shared"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
