apiVersion: v1
kind: Service
metadata:
  name: {{ include "homepage.fullname" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
  {{- with .Values.service.main.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.main.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.main.ports.http.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "homepage.selectorLabels" . | nindent 4 }}
