apiVersion: v1
data:
  config_webrx.py: |
    sdrs = {
      "rtlsdr": {
        "name": "RTL-SDR USB Stick",
        "type": "rtl_sdr",
        "ppm": 0,
        "profiles": {},
      },
    }
    x = 1
    samp_rate = 2400000 #2.4 MHz
    for start_freq in range(88000000, 108000000, (samp_rate - 100000)):
      fm_profile = {
        "name": "FM Radio " + str(x),
        "center_freq": start_freq + (samp_rate / 2),
        "rf_gain": 29,
        "samp_rate": samp_rate,
        "start_freq": start_freq,
        "start_mod": "wfm",
      }
      sdrs["rtlsdr"]["profiles"]["FM" + str(x)] = fm_profile
      x+=1
    x=0
    # samp_rate = 2400000 #2.4 MHz
    # for start_freq in range(162400000, 162550000, (samp_rate - 100000)):
    #   fm_profile = {
    #     "name": "NOAA WX " + str(x),
    #     "center_freq": start_freq + (samp_rate / 2),
    #     "rf_gain": 29,
    #     "samp_rate": samp_rate,
    #     "start_freq": start_freq,
    #     "start_mod": "wfm",
    #   }
    #   sdrs["rtlsdr"]["profiles"]["FM" + str(x)] = fm_profile
    #   x+=1
kind: ConfigMap
metadata:
  name: {{ include "openwebrx.fullname" . }}-config

